variables:
  isMasterBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isReleaseBranch: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]
  azureArtifactsBranch: $[or(eq(variables.isMasterBranch, true), eq(variables.isReleaseBranch, true))]
  nugetOrgBranch: $[eq(variables.isReleaseBranch, true)]

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: false
  branches:
    include:
    - master
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - 'readme.md'
    - 'docs/*'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'ci'

- task: Npm@1
  displayName: 'npm run package'
  inputs:
    command: 'custom'
    customCommand: 'run package'

- task: CopyFiles@2
  displayName: 'copy VSIX package to Artifact Staging Directory'
  inputs:
    SourceFolder: '.'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/extension'

- task: PublishBuildArtifacts@1
  displayName: 'publish vsix build artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/extension'
    artifactName: 'VSIX-package'
