variables:
  isMasterBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isReleaseBranch: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]
  azureArtifactsBranch: $[or(eq(variables.isMasterBranch, true), eq(variables.isReleaseBranch, true))]
  nugetOrgBranch: $[eq(variables.isReleaseBranch, true)]

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: false
  branches:
    include:
    - master
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - 'readme.md'
    - 'docs/*'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'ci'

- script: |
    npx gulp setversion
    npx vsce package --out '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'publish vsix build artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'VSIX-package'
